import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="scroll-smooth h-full">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-gray-800 flex flex-col min-h-screen`}
            >
                <header className="bg-white shadow-md">
                    <div className="max-w-6xl mx-auto p-4 flex justify-between items-center">
                        <h1 className="text-2xl font-semibold text-indigo-600">
                          Shahnewaz's Portfolio
                        </h1>
                        <nav>
                            <ul className="flex gap-8 text-lg font-medium">
                                <li>
                                    <Link href="/about" className="hover:text-indigo-500">
                                        About
                                    </Link>
                                </li>
                                <li>
                                    <Link href="/projects" className="hover:text-indigo-500">
                                        Projects
                                    </Link>
                                </li>
                                <li>
                                    <Link href="/contact" className="hover:text-indigo-500">
                                        Contact
                                    </Link>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </header>

                <main className="flex-grow max-w-6xl mx-auto p-6 mt-10">
                    {children}
                </main>

                <footer className="bg-gray-900 text-gray-200">
                    <div className="max-w-6xl mx-auto p-6 flex flex-col items-center md:flex-row md:justify-between">
                        <p className="text-center text-sm md:text-base">
                            © 2024 My Portfolio. All Rights Reserved.
                        </p>
                        <div className="flex space-x-6 mt-4 md:mt-0">
                            <a
                                href="#"
                                className="hover:text-indigo-400 transition-colors duration-300"
                            >
                                LinkedIn
                            </a>
                            <a
                                href="#"
                                className="hover:text-indigo-400 transition-colors duration-300"
                            >
                                GitHub
                            </a>
                            <a
                                href="#"
                                className="hover:text-indigo-400 transition-colors duration-300"
                            >
                                Twitter
                            </a>
                        </div>
                    </div>
                </footer>
            </body>
        </html>
    );
}
